import type { Currency, ProviderName, TZSAmount } from './core';
import type { PaymentStatus } from './order';

/**
 * Event types emitted after webhook verification and persistence.
 *
 * Use these with {@link PesaInstance.on} to react to payment activity:
 *
 * @example
 * ```ts
 * pesa.on('PAYMENT_SUCCESS', async (event) => {
 *   await db.orders.update({
 *     id:     event.reference,
 *     status: 'paid',
 *   });
 * });
 *
 * pesa.on('DISBURSEMENT_FAILED', async (event) => {
 *   await notifySupport(event);
 * });
 * ```
 */
export type PaymentEventType =
  | 'PAYMENT_SUCCESS'
  | 'PAYMENT_FAILED'
  | 'PAYMENT_PENDING'
  | 'DISBURSEMENT_SUCCESS'
  | 'DISBURSEMENT_FAILED';

/**
 * Normalized payment event — the **source of truth** for all payment activity.
 *
 * Every webhook received and verified is parsed by the provider adapter,
 * normalized into a `PaymentEvent`, persisted to the event store, and
 * emitted to registered handlers.
 *
 * @example
 * ```ts
 * // Accessing event data in a handler
 * pesa.on('PAYMENT_SUCCESS', (event) => {
 *   console.log(`Payment ${event.reference} succeeded`);
 *   console.log(`Amount: TZS ${event.amount}`);
 *   console.log(`Provider: ${event.provider}`);
 * });
 * ```
 */
export interface PaymentEvent {
  /** UUID generated by the SDK. */
  id: string;
  /** Event type (PAYMENT_SUCCESS, DISBURSEMENT_FAILED, etc.). */
  type: PaymentEventType;
  /** Provider-assigned transaction ID. */
  orderId: string;
  /** Your merchant reference. */
  reference: string;
  /** Amount in whole TZS. */
  amount: TZSAmount;
  /** Currency code. */
  currency: Currency;
  /** Normalized payment status. */
  status: PaymentStatus;
  /** Which provider processed this payment. */
  provider: ProviderName;
  /** When the event occurred. */
  timestamp: Date;
  /** Arbitrary metadata attached to the event. */
  metadata?: Record<string, unknown>;
  /** Raw provider webhook payload. Escape hatch — prefer normalized fields. */
  raw?: unknown;
}
