import type { TZSAmount, Currency, ProviderName } from './core';
import type { PaymentStatus } from './order';

/**
 * Event types that can be emitted after webhook verification and persistence.
 */
export type PaymentEventType =
  | 'PAYMENT_SUCCESS'
  | 'PAYMENT_FAILED'
  | 'PAYMENT_PENDING'
  | 'DISBURSEMENT_SUCCESS'
  | 'DISBURSEMENT_FAILED';

/**
 * Every webhook received and verified is normalized into a PaymentEvent
 * and persisted to the event store. This is the source of truth for all
 * payment activity in the SDK.
 */
export interface PaymentEvent {
  id:         string;           // UUID — generated by SDK
  type:       PaymentEventType;
  orderId:    string;
  reference:  string;
  amount:     TZSAmount;
  currency:   Currency;
  status:     PaymentStatus;
  provider:   ProviderName;
  timestamp:  Date;
  metadata?:  Record<string, unknown>;
  raw?:       unknown;
}
